//type  1:黑体 2:宋体 3:楷体 4:艺术字体 5:手绘体
var fontsMap = {
    SiYuanSongTi_Regular: {
        type: '2',
        code: 'siyuansongti',
        name: '思源宋体',
        preview: 'images/font/siyuansongti/preview.svg',
        posters: ['images/font/siyuansongti/poster.svg'],
        auth: false,
        license: 'OFL-1.1',
        source: 'https://github.com/adobe-fonts/source-han-serif',
        download: '',
        desc: '「思源宋体」是 Adobe Type 发布的最新泛 CJK 字体，它是对应于<a target="blank" href="https://blog.typekit.com/alternate/source-han-sans-chs/" >思源黑体</a>的宋体字体；我们发布这两种字体是为了响应统一设计的需求，以服务于东亚 15 亿人口。\n思源宋体支持四种不同的东亚语言（简体中文、繁体中文、日语和朝鲜语），7 种粗细类型中的每一种都有 65,535 个字形，可共同呈现一致的视觉美感。该字体还包含多个西方字形，支持拉丁语、希腊语和西里尔文脚本，这些字形均来源于 <a target="blank" href="https://blog.typekit.com/2017/01/10/introducing-source-serif-2-0/">Source Serif</a>。'
    },
    SiYuanHeiTi_Regular: {
        type: '1',
        code: 'siyuanheiti',
        name: '思源黑体',
        preview: 'images/font/siyuanheiti/preview.svg',
        posters: ['images/font/siyuanheiti/poster.svg'],
        license: 'OFL-1.1',
        auth: false,
        source: 'https://github.com/adobe-fonts/source-han-sans',
        download: '',
        desc: '「思源黑体」是一套 OpenType/CFF 泛中日韩字体。这个开源项目不仅提供了可用的 OpenType 字体，还提供了利用 AFDKO <b>makeotf</b> 和 <b>otf2otc</b> 工具创建这些 OpenType 字体时的所有源文件。'
    },
    FangZhengShuSong_Regular: {
        type: '2',
        code: 'fangzhengshusong',
        name: '方正书宋',
        preview: 'images/font/fangzhengshusong/preview.svg',
        posters: ['images/font/fangzhengshusong/poster.svg'],
        born: '20191225',
        version: '',
        license: '商免',
        auth: true,
        source: 'https://www.foundertype.com/index.php/About/bookAuth/key/my_sysq.html',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E6%96%B9%E6%AD%A3%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E6%96%B9%E6%AD%A3%E4%B9%A6%E5%AE%8B%E7%AE%80%E4%BD%93.ttf',
        desc: '「方正书宋」源自上海印刷技术研究所的宋二，原字形距今已有近60年。最初的设计就是专门针对最常用的小字号正文排版。方正书宋的字形端正清秀，中宫适度。凭着清晰爽目、久读不易疲劳、印刷适性好的优点，长期被作为杂志和书籍的正文首选字体，所以也是一款非常经典的正文宋体。'
    },
    FangZhengFangSong_Regular: {
        type: '2',
        code: 'fangzhengfangsong',
        name: '方正仿宋',
        preview: 'images/font/fangzhengfangsong/preview.svg',
        posters: ['images/font/fangzhengfangsong/poster.svg'],
        license: '商免',
        auth: true,
        source: 'https://www.foundertype.com/index.php/About/bookAuth/key/my_sysq.html',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E6%96%B9%E6%AD%A3%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E6%96%B9%E6%AD%A3%E4%BB%BF%E5%AE%8B%E7%AE%80%E4%BD%93.ttf',
        desc: '「仿宋体」产生于20世纪初，由当时的铅字制作者仿宋版书中的瘦细字体而制成。方正仿宋源于铅字时代的字稿，其字身略窄，笔画瘦硬，横竖笔画等粗，起笔处有斜势棱角，折笔处棱角分明，整体字形挺拔俊秀，给人以悦目之感。因清晰美观，容易辨认，长期被用于工程图纸文字和书刊中的引文。'
    },
    FangZhengHeiTi_Regular: {
        type: '1',
        code: 'fangzhengheiti',
        name: '方正黑体',
        preview: 'images/font/fangzhengheiti/preview.svg',
        posters: ['images/font/fangzhengheiti/poster.svg'],
        license: '商免',
        auth: true,
        source: 'https://www.foundertype.com/index.php/About/bookAuth/key/my_sysq.html',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E6%96%B9%E6%AD%A3%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E6%96%B9%E6%AD%A3%E9%BB%91%E4%BD%93%E7%AE%80%E4%BD%93.ttf',
        desc: '「方正黑体」的设计源于铅字时代的黑体字稿，是一款专门为正文排版设计的黑体。方正黑体的笔画两端留有喇叭口，撇、捺、钩笔画的粗细变化较大，中宫比较紧凑。其字重适中、字形风格中性朴实，不但适用于印刷媒介，还可用于屏幕阅读，是一款非常经典的正文黑体。'
    },
    FangZhengKaiTi_Regular: {
        type: '3',
        code: 'fangzhengkaiti',
        name: '方正楷体',
        preview: 'images/font/fangzhengkaiti/preview.svg',
        posters: ['images/font/fangzhengkaiti/poster.svg'],
        license: '商免',
        auth: true,
        source: 'https://www.foundertype.com/index.php/About/bookAuth/key/my_sysq.html',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E6%96%B9%E6%AD%A3%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E6%96%B9%E6%AD%A3%E6%A5%B7%E4%BD%93%E7%AE%80%E4%BD%93.ttf',
        desc: '「方正楷体」源于上海印刷技术研究所“华文楷体”字稿。原“华文楷体”诞生于20世纪40年代，新中国成立后一直是主要使用的铅字楷体。在此期间，上海字模一厂、上海印刷技术研究所等单位进行了数次改良，并添加了简体字。方正楷体的结构秀丽匀称，笔画圆润柔和，横竖笔画的粗细变化不大。这款字体被大量应用于报纸、杂志和书籍中的正文，在教科书中最为常见。'
    },
    PangMenZhengDaoBiaoTiTi_Regular: {
        type: '4',
        code: 'pangmenzhengdaobiaotiti',
        name: '庞门正道标题体',
        preview: 'images/font/pangmenzhengdaobiaotiti/preview.svg',
        posters: ['images/font/pangmenzhengdaobiaotiti/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://mp.weixin.qq.com/s/1ccpLCOrIn81JhV9ulwPIQ',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E5%BA%9E%E9%97%A8%E6%AD%A3%E9%81%93%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E5%BA%9E%E9%97%A8%E6%AD%A3%E9%81%93%E6%A0%87%E9%A2%98%E4%BD%93.ttf',
        desc: '「庞门正道标题体」由庞门正道联合了13位设计师于2016年推出的第一款免费商用字体。'
    },
    PangMenZhengDaoCuShuTi_Regular: {
        type: '5',
        code: 'pangmenzhengdaocushuti',
        name: '庞门正道粗书体',
        preview: 'images/font/pangmenzhengdaocushuti/preview.svg',
        posters: ['images/font/pangmenzhengdaocushuti/poster.svg',
            'https://mmbiz.qpic.cn/mmbiz_jpg/Rhh4hWLlib1aCOKB8XqaBQKuRpDtoibaicPmrsic5oAZgexII9hdK9q3N69CHEN5GsySiatYUF67w96MYStkqibFPTEQ/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1',
            'https://mmbiz.qpic.cn/mmbiz_jpg/Rhh4hWLlib1aCOKB8XqaBQKuRpDtoibaicPbxjqV2LhAbt1XmhLu6qGlKIcqEib7aLgicusT3ibGBRbibpfGPKZicqsI4w/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1',
            'https://mmbiz.qpic.cn/mmbiz_jpg/Rhh4hWLlib1aCOKB8XqaBQKuRpDtoibaicPnz03EOjGLbssVCVs7lEhP91txDeIseDAPaqB0cYDoDSjU6DoxE7d7A/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1',
            'https://mmbiz.qpic.cn/mmbiz_jpg/Rhh4hWLlib1aCOKB8XqaBQKuRpDtoibaicPwahmexYZg0TpHibVEmqic3bxtECPApx5RCibEJwDibSsdKb4SB91dkbxTA/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1',
            'https://mmbiz.qpic.cn/mmbiz_jpg/Rhh4hWLlib1aCOKB8XqaBQKuRpDtoibaicPMWfzhuwjEvfY92YGibTcGYibhU2AlcLVpPspmlmD0093stbklLvcHVcA/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1',
            'https://mmbiz.qpic.cn/mmbiz_jpg/Rhh4hWLlib1aCOKB8XqaBQKuRpDtoibaicPMicB2A4UgZADkT2Omeu7g8rjHLyPfu1BHI5jvfcqsBA600F7Glia4a7w/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1'
        ],
        license: '商免',
        auth: false,
        source: 'https://mp.weixin.qq.com/s/LZ_PMNc-3uX-Atmri4OLGQ',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E5%BA%9E%E9%97%A8%E6%AD%A3%E9%81%93%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E5%BA%9E%E9%97%A8%E6%AD%A3%E9%81%93%E7%B2%97%E4%B9%A6%E4%BD%93.ttf',
        desc: '「庞门正道粗书体」由庞门正道公众号2018年发布的第二款免费商用字体，由车港敏设计完成'
    },
    PangMenZhengDaoQingSongTi_Regular: {
        type: '4',
        code: 'pangmenzhengdaoqingsongti',
        name: '庞门正道轻松体',
        preview: 'images/font/pangmenzhengdaoqingsongti/preview.svg',
        posters: ['images/font/pangmenzhengdaoqingsongti/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://mp.weixin.qq.com/s/1ccpLCOrIn81JhV9ulwPIQ',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E5%BA%9E%E9%97%A8%E6%AD%A3%E9%81%93%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E5%BA%9E%E9%97%A8%E6%AD%A3%E9%81%93%E8%BD%BB%E6%9D%BE%E4%BD%93.otf',
        desc: '「庞门正道轻松体」由庞门正道在2019年发布的第三款免费字体。'
    },
    ZhanKuGaoDuanHei_Regular: {
        type: '4',
        code: 'zhankugaoduanhei',
        name: '站酷高端黑',
        preview: 'images/font/zhankugaoduanhei/preview.svg',
        posters: ['images/font/zhankugaoduanhei/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://www.zcool.com.cn/article/ZMTQyOTUy.html',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%AB%99%E9%85%B7%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%20%E7%AB%99%E9%85%B7%E9%AB%98%E7%AB%AF%E9%BB%91.ttf',
        desc: '「站酷高端黑」由字体设计师胡晓波、刘兵克发起，参与汉字百人舞100位字体设计师共同完成。是2014年圣诞发布的第一款由站酷冠名的公益字体，字体设计师胡晓波、刘兵克在站酷网发起“汉字百人舞”的征集设计师集体造字，前后参与设计师近百人。2014年12月发布第一版，2015年11月发布最新修订版。包含6763个汉字、数字和英文字母。「庞门正道轻松体」由庞门正道在2019年发布的第三款免费字体。'
    },
    ZhanKuWenYiTi_Regular: {
        type: '4',
        code: 'zhankuwenyiti',
        name: '站酷文艺体',
        preview: 'images/font/zhankuwenyiti/preview.svg',
        posters: ['images/font/zhankuwenyiti/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://www.zcool.com.cn/work/ZMjc2NDA5NDA=.html',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%AB%99%E9%85%B7%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%AB%99%E9%85%B7%E6%96%87%E8%89%BA%E4%BD%93.ttf',
        desc: '「站酷文艺体」由字体设计师刘兵克确定字形和规范，由刘兵克工作室以及刘兵克字体设计直播课学员共同创作完成，设计师郑庆科完成了最终的字库生成工作。字形新颖独特，简洁有力，清新淡雅，文艺范十足。包含7155个常用字，52个英文字母，10 个阿拉伯数字，67个常用标点及符号。'
    },
    ZhanKuXiaoWeiLOGOTi_Regular: {
        type: '4',
        code: 'zhankuxiaoweilogo',
        name: '站酷小微LOGO体',
        preview: 'images/font/zhankuxiaoweilogo/preview.svg',
        posters: ['images/font/zhankuxiaoweilogo/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://www.zcool.com.cn/special/zcoolfonts/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%AB%99%E9%85%B7%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%AB%99%E9%85%B7%E5%B0%8F%E8%96%87LOGO%E4%BD%93.otf',
        desc: '「站酷小微LOGO体」由上海佐兹品牌设计工作室设计总监李大卫 (David 小马哥）带领其工作室团队共成完成。是李大卫送给自己女儿出生三周年的一个礼物。其目的是为了填补免费字体中的LOGO体空缺。字体笔画浑厚，识别性高,放大放小空间间隙都能如意灵通。2018年1月最新修订版。采用GB2312汉字编码，共收录6763个汉字。'
    },
    ZhanKuQingKeHuangYouTi_Regular: {
        type: '4',
        code: 'zhankuqingkehuangyouti',
        name: '站酷庆科黄油体',
        preview: 'images/font/zhankuqingkehuangyouti/preview.svg',
        posters: ['images/font/zhankuqingkehuangyouti/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://www.zcool.com.cn/work/ZMTg5MDEyMDQ=.html',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%AB%99%E9%85%B7%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%AB%99%E9%85%B7%E5%BA%86%E7%A7%91%E9%BB%84%E6%B2%B9%E4%BD%93.ttf',
        desc: '「站酷庆科黄油体」，由字体设计师郑庆科开发，线条圆润。并且字体数量多，达到了9千个多个汉字。站酷庆科黄油体是一款字型创新、线条圆润的字体。笔划的每一个直角，都被处理成了半径为4pt的圆角。在设计中需遵循笔划简化但不省略，笔划角度尽量为垂直角度。字体部首的右下角均为45°缺角，提高了字体视觉中心，并有效的解决了一些字体因笔划交叉，字体阅读困难的毛病。'
    },
    ZhanKuKuHei_Regular: {
        type: '4',
        code: 'zhankukuhei',
        name: '站酷酷黑',
        preview: 'images/font/zhankukuhei/preview.svg',
        posters: ['images/font/zhankukuhei/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://www.zcool.com.cn/work/ZMTc2MDM5MTY=.html',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%AB%99%E9%85%B7%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%AB%99%E9%85%B7%E9%85%B7%E9%BB%91%E4%BD%93.ttf',
        desc: '「站酷酷黑」由胡晓波发起，字游工作室成员进行基础字形设计。胡晓波设计班十名学员共同设计完成。[站酷酷黑体验版］在站酷十周年之际横空出世。字形笔画粗犷有力，用宽扁型的字面构建出厚重的字体形态，笔画细节上的修饰既增强了字体的设计感，又让字体多了一些小小的精致感，中宫的饱满使得文字之间的排版组合非常醒目好看。2016年7月发布体验版。包含3500个常用字，52个英文字母，10个阿拉伯数字。'
    },
    ZhanKuKuaiLeTi_Regular: {
        type: '4',
        code: 'zhankukuaileti',
        name: '站酷快乐体',
        preview: 'images/font/zhankukuaileti/preview.svg',
        posters: ['images/font/zhankukuaileti/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://www.zcool.com.cn/work/ZMTMzMDQ0Mjg=.html',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%AB%99%E9%85%B7%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%AB%99%E9%85%B7%E5%BF%AB%E4%B9%90%E4%BD%93.ttf',
        desc: '「站酷快乐体」由刘兵克学员和工作室团队设计。是在“站酷快乐体”基础上耗时7个月进行的大幅修改与提升，经过多轮校审之后已正式对外公布并提供下载。2015年9月发布第一版，2016年6月发布最新修订版。采用GB2312汉字编码，共收录6763个汉字。'
    }

};