var baseUrl = 'https://cdn.jsdelivr.net/gh/wordshub/free-font/';
//type  1:黑体 2:宋体 3:楷体 4:艺术字体 5:手绘体
var fontsMap = {
    SiYuanSongTi_Regular: {
        type: '2',
        code: 'siyuansongti',
        name: '思源宋体',
        preview: 'images/font/siyuansongti/font.svg',
        posters: ['images/font/siyuansongti/poster.svg'],
        auth: false,
        license: 'OFL-1.1',
        source: 'https://github.com/adobe-fonts/source-han-serif',
        download: '',
        desc: '「思源宋体」是 Adobe Type 发布的最新泛 CJK 字体，它是对应于<a target="blank" href="https://blog.typekit.com/alternate/source-han-sans-chs/" >思源黑体</a>的宋体字体；我们发布这两种字体是为了响应统一设计的需求，以服务于东亚 15 亿人口。\n思源宋体支持四种不同的东亚语言（简体中文、繁体中文、日语和朝鲜语），7 种粗细类型中的每一种都有 65,535 个字形，可共同呈现一致的视觉美感。该字体还包含多个西方字形，支持拉丁语、希腊语和西里尔文脚本，这些字形均来源于 <a target="blank" href="https://blog.typekit.com/2017/01/10/introducing-source-serif-2-0/">Source Serif</a>。'
    },
    SiYuanHeiTi_Regular: {
        type: '1',
        code: 'siyuanheiti',
        name: '思源黑体',
        preview: 'images/font/siyuanheiti/font.svg',
        posters: ['images/font/siyuanheiti/poster.svg'],
        license: 'OFL-1.1',
        auth: false,
        source: 'https://github.com/adobe-fonts/source-han-sans',
        download: '',
        desc: '「思源黑体」是一套 OpenType/CFF 泛中日韩字体。这个开源项目不仅提供了可用的 OpenType 字体，还提供了利用 AFDKO <b>makeotf</b> 和 <b>otf2otc</b> 工具创建这些 OpenType 字体时的所有源文件。'
    },
    FangZhengShuSong_Regular: {
        type: '2',
        code: 'fangzhengshusong',
        name: '方正书宋',
        preview: 'images/font/fangzhengshusong/font.svg',
        posters: ['images/font/fangzhengshusong/poster.svg'],
        born: '20191225',
        version: '',
        license: '商免',
        auth: true,
        source: 'https://www.foundertype.com/index.php/About/bookAuth/key/my_sysq.html',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E6%96%B9%E6%AD%A3%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E6%96%B9%E6%AD%A3%E4%B9%A6%E5%AE%8B%E7%AE%80%E4%BD%93.ttf',
        desc: '「方正书宋」源自上海印刷技术研究所的宋二，原字形距今已有近60年。最初的设计就是专门针对最常用的小字号正文排版。方正书宋的字形端正清秀，中宫适度。凭着清晰爽目、久读不易疲劳、印刷适性好的优点，长期被作为杂志和书籍的正文首选字体，所以也是一款非常经典的正文宋体。'
    },
    FangZhengFangSong_Regular: {
        type: '2',
        code: 'fangzhengfangsong',
        name: '方正仿宋',
        preview: 'images/font/fangzhengfangsong/font.svg',
        posters: ['images/font/fangzhengfangsong/poster.svg'],
        license: '商免',
        auth: true,
        source: 'https://www.foundertype.com/index.php/About/bookAuth/key/my_sysq.html',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E6%96%B9%E6%AD%A3%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E6%96%B9%E6%AD%A3%E4%BB%BF%E5%AE%8B%E7%AE%80%E4%BD%93.ttf',
        desc: '「仿宋体」产生于20世纪初，由当时的铅字制作者仿宋版书中的瘦细字体而制成。方正仿宋源于铅字时代的字稿，其字身略窄，笔画瘦硬，横竖笔画等粗，起笔处有斜势棱角，折笔处棱角分明，整体字形挺拔俊秀，给人以悦目之感。因清晰美观，容易辨认，长期被用于工程图纸文字和书刊中的引文。'
    },
    FangZhengHeiTi_Regular: {
        type: '1',
        code: 'fangzhengheiti',
        name: '方正黑体',
        preview: 'images/font/fangzhengheiti/font.svg',
        posters: ['images/font/fangzhengheiti/poster.svg'],
        license: '商免',
        auth: true,
        source: 'https://www.foundertype.com/index.php/About/bookAuth/key/my_sysq.html',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E6%96%B9%E6%AD%A3%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E6%96%B9%E6%AD%A3%E9%BB%91%E4%BD%93%E7%AE%80%E4%BD%93.ttf',
        desc: '「方正黑体」的设计源于铅字时代的黑体字稿，是一款专门为正文排版设计的黑体。方正黑体的笔画两端留有喇叭口，撇、捺、钩笔画的粗细变化较大，中宫比较紧凑。其字重适中、字形风格中性朴实，不但适用于印刷媒介，还可用于屏幕阅读，是一款非常经典的正文黑体。'
    },
    FangZhengKaiTi_Regular: {
        type: '3',
        code: 'fangzhengkaiti',
        name: '方正楷体',
        preview: 'images/font/fangzhengkaiti/font.svg',
        posters: ['images/font/fangzhengkaiti/poster.svg'],
        license: '商免',
        auth: true,
        source: 'https://www.foundertype.com/index.php/About/bookAuth/key/my_sysq.html',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E6%96%B9%E6%AD%A3%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E6%96%B9%E6%AD%A3%E6%A5%B7%E4%BD%93%E7%AE%80%E4%BD%93.ttf',
        desc: '「方正楷体」源于上海印刷技术研究所“华文楷体”字稿。原“华文楷体”诞生于20世纪40年代，新中国成立后一直是主要使用的铅字楷体。在此期间，上海字模一厂、上海印刷技术研究所等单位进行了数次改良，并添加了简体字。方正楷体的结构秀丽匀称，笔画圆润柔和，横竖笔画的粗细变化不大。这款字体被大量应用于报纸、杂志和书籍中的正文，在教科书中最为常见。'
    },
    PangMenZhengDaoBiaoTiTi_Regular: {
        type: '4',
        code: 'pangmenzhengdaobiaotiti',
        name: '庞门正道标题体',
        preview: 'images/font/pangmenzhengdaobiaotiti/font.svg',
        posters: ['images/font/pangmenzhengdaobiaotiti/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://mp.weixin.qq.com/s/1ccpLCOrIn81JhV9ulwPIQ',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E5%BA%9E%E9%97%A8%E6%AD%A3%E9%81%93%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E5%BA%9E%E9%97%A8%E6%AD%A3%E9%81%93%E6%A0%87%E9%A2%98%E4%BD%93.ttf',
        desc: '「庞门正道标题体」由庞门正道联合了13位设计师于2016年推出的第一款免费商用字体。'
    },
    PangMenZhengDaoCuShuTi_Regular: {
        type: '5',
        code: 'pangmenzhengdaocushuti',
        name: '庞门正道粗书体',
        preview: 'images/font/pangmenzhengdaocushuti/font.svg',
        posters: ['images/font/pangmenzhengdaocushuti/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://mp.weixin.qq.com/s/LZ_PMNc-3uX-Atmri4OLGQ',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E5%BA%9E%E9%97%A8%E6%AD%A3%E9%81%93%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E5%BA%9E%E9%97%A8%E6%AD%A3%E9%81%93%E7%B2%97%E4%B9%A6%E4%BD%93.ttf',
        desc: '「庞门正道粗书体」由庞门正道公众号2018年发布的第二款免费商用字体，由车港敏设计完成'
    },
    PangMenZhengDaoQingSongTi_Regular: {
        type: '4',
        code: 'pangmenzhengdaoqingsongti',
        name: '庞门正道轻松体',
        preview: 'images/font/pangmenzhengdaoqingsongti/font.svg',
        posters: ['images/font/pangmenzhengdaoqingsongti/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://mp.weixin.qq.com/s/1ccpLCOrIn81JhV9ulwPIQ',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E5%BA%9E%E9%97%A8%E6%AD%A3%E9%81%93%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E5%BA%9E%E9%97%A8%E6%AD%A3%E9%81%93%E8%BD%BB%E6%9D%BE%E4%BD%93.otf',
        desc: '「庞门正道轻松体」由庞门正道在2019年发布的第三款免费字体。'
    },
    ZhanKuGaoDuanHei_Regular: {
        type: '4',
        code: 'zhankugaoduanhei',
        name: '站酷高端黑',
        preview: 'images/font/zhankugaoduanhei/font.svg',
        posters: ['images/font/zhankugaoduanhei/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://www.zcool.com.cn/article/ZMTQyOTUy.html',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%AB%99%E9%85%B7%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%20%E7%AB%99%E9%85%B7%E9%AB%98%E7%AB%AF%E9%BB%91.ttf',
        desc: '「站酷高端黑」由字体设计师胡晓波、刘兵克发起，参与汉字百人舞100位字体设计师共同完成。是2014年圣诞发布的第一款由站酷冠名的公益字体，字体设计师胡晓波、刘兵克在站酷网发起“汉字百人舞”的征集设计师集体造字，前后参与设计师近百人。2014年12月发布第一版，2015年11月发布最新修订版。包含6763个汉字、数字和英文字母。「庞门正道轻松体」由庞门正道在2019年发布的第三款免费字体。'
    },
    ZhanKuWenYiTi_Regular: {
        type: '4',
        code: 'zhankuwenyiti',
        name: '站酷文艺体',
        preview: 'images/font/zhankuwenyiti/font.svg',
        posters: ['images/font/zhankuwenyiti/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://www.zcool.com.cn/work/ZMjc2NDA5NDA=.html',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%AB%99%E9%85%B7%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%AB%99%E9%85%B7%E6%96%87%E8%89%BA%E4%BD%93.ttf',
        desc: '「站酷文艺体」由字体设计师刘兵克确定字形和规范，由刘兵克工作室以及刘兵克字体设计直播课学员共同创作完成，设计师郑庆科完成了最终的字库生成工作。字形新颖独特，简洁有力，清新淡雅，文艺范十足。包含7155个常用字，52个英文字母，10 个阿拉伯数字，67个常用标点及符号。'
    },
    ZhanKuXiaoWeiLOGOTi_Regular: {
        type: '4',
        code: 'zhankuxiaoweilogo',
        name: '站酷小微LOGO体',
        preview: 'images/font/zhankuxiaoweilogo/font.svg',
        posters: ['images/font/zhankuxiaoweilogo/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://www.zcool.com.cn/special/zcoolfonts/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%AB%99%E9%85%B7%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%AB%99%E9%85%B7%E5%B0%8F%E8%96%87LOGO%E4%BD%93.otf',
        desc: '「站酷小微LOGO体」由上海佐兹品牌设计工作室设计总监李大卫 (David 小马哥）带领其工作室团队共成完成。是李大卫送给自己女儿出生三周年的一个礼物。其目的是为了填补免费字体中的LOGO体空缺。字体笔画浑厚，识别性高,放大放小空间间隙都能如意灵通。2018年1月最新修订版。采用GB2312汉字编码，共收录6763个汉字。'
    },
    ZhanKuQingKeHuangYouTi_Regular: {
        type: '4',
        code: 'zhankuqingkehuangyouti',
        name: '站酷庆科黄油体',
        preview: 'images/font/zhankuqingkehuangyouti/font.svg',
        posters: ['images/font/zhankuqingkehuangyouti/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://www.zcool.com.cn/work/ZMTg5MDEyMDQ=.html',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%AB%99%E9%85%B7%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%AB%99%E9%85%B7%E5%BA%86%E7%A7%91%E9%BB%84%E6%B2%B9%E4%BD%93.ttf',
        desc: '「站酷庆科黄油体」，由字体设计师郑庆科开发，线条圆润。并且字体数量多，达到了9千个多个汉字。站酷庆科黄油体是一款字型创新、线条圆润的字体。笔划的每一个直角，都被处理成了半径为4pt的圆角。在设计中需遵循笔划简化但不省略，笔划角度尽量为垂直角度。字体部首的右下角均为45°缺角，提高了字体视觉中心，并有效的解决了一些字体因笔划交叉，字体阅读困难的毛病。'
    },
    ZhanKuKuHei_Regular: {
        type: '4',
        code: 'zhankukuhei',
        name: '站酷酷黑',
        preview: 'images/font/zhankukuhei/font.svg',
        posters: ['images/font/zhankukuhei/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://www.zcool.com.cn/work/ZMTc2MDM5MTY=.html',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%AB%99%E9%85%B7%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%AB%99%E9%85%B7%E9%85%B7%E9%BB%91%E4%BD%93.ttf',
        desc: '「站酷酷黑」由胡晓波发起，字游工作室成员进行基础字形设计。胡晓波设计班十名学员共同设计完成。[站酷酷黑体验版］在站酷十周年之际横空出世。字形笔画粗犷有力，用宽扁型的字面构建出厚重的字体形态，笔画细节上的修饰既增强了字体的设计感，又让字体多了一些小小的精致感，中宫的饱满使得文字之间的排版组合非常醒目好看。2016年7月发布体验版。包含3500个常用字，52个英文字母，10个阿拉伯数字。'
    },
    ZhanKuKuaiLeTi_Regular: {
        type: '4',
        code: 'zhankukuaileti',
        name: '站酷快乐体',
        preview: 'images/font/zhankukuaileti/font.svg',
        posters: ['images/font/zhankukuaileti/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://www.zcool.com.cn/work/ZMTMzMDQ0Mjg=.html',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%AB%99%E9%85%B7%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%AB%99%E9%85%B7%E5%BF%AB%E4%B9%90%E4%BD%93.ttf',
        desc: '「站酷快乐体」由刘兵克学员和工作室团队设计。是在“站酷快乐体”基础上耗时7个月进行的大幅修改与提升，经过多轮校审之后已正式对外公布并提供下载。2015年9月发布第一版，2016年6月发布最新修订版。采用GB2312汉字编码，共收录6763个汉字。'
    },
    HuXiaoBoNanShenTi_Regular: {
        type: '4',
        code: 'huxiaobonanshenti',
        name: '胡晓波男神体',
        preview: 'images/font/huxiaobonanshenti/font.svg',
        posters: ['images/font/huxiaobonanshenti/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://www.zcool.com.cn/work/ZNDE3NjcwMTY=.html',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E8%83%A1%E6%99%93%E6%B3%A2%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E8%83%A1%E6%99%93%E6%B3%A2%E7%94%B7%E7%A5%9E%E4%BD%93.otf',
        desc: '「胡晓波男神体」由设计师胡晓波设计的一款免费字体'
    },
    HuXiaoBoSaoBaoTi_Regular: {
        type: '4',
        code: 'huxiaobosaobaoti',
        name: '胡晓波骚包体',
        preview: 'images/font/huxiaobosaobaoti/font.svg',
        posters: ['images/font/huxiaobosaobaoti/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://www.zcool.com.cn/work/ZNDE3NjcwMTY=.html',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E8%83%A1%E6%99%93%E6%B3%A2%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E8%83%A1%E6%99%93%E6%B3%A2%E9%AA%9A%E5%8C%85%E4%BD%93.otf',
        desc: '「胡晓波骚包体」由设计师胡晓波设计的一款免费字体'
    },
    HuXiaoBoZhenShuaiTi_Regular: {
        type: '4',
        code: 'huxiaobozhenshuaiti',
        name: '胡晓波真帅体',
        preview: 'images/font/huxiaobozhenshuaiti/font.svg',
        posters: ['images/font/huxiaobozhenshuaiti/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://www.zcool.com.cn/work/ZNDE3NjcwMTY=.html',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E8%83%A1%E6%99%93%E6%B3%A2%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E8%83%A1%E6%99%93%E6%B3%A2%E7%9C%9F%E5%B8%85%E4%BD%93.otf',
        desc: '「胡晓波真帅体」是由设计师胡晓波设计的一款免费字体'
    },
    MuYaoRuanBiShouXieTi_Regular: {
        type: '5',
        code: 'muyaoruanbishouxieti',
        name: '沐瑶软笔手写体',
        preview: 'images/font/muyaoruanbishouxieti/font.svg',
        posters: ['images/font/muyaoruanbishouxieti/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://www.zcool.com.cn/work/ZMjg5MjAwMDQ=.html',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E6%B2%90%E7%91%B6%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E6%B2%90%E7%91%B6%E8%BD%AF%E7%AC%94%E6%89%8B%E5%86%99%E4%BD%93.ttf',
        desc: '「沐瑶软笔手写体」（Muyao-Softbrush ） 是一款手写体，自来站酷设计师@春颜秋色送给女儿的礼物。也是以女儿名字命名的一款可免费商用的手写字体。遵循GB2312标准，共包含6763个汉字加数字英文和常用标点。'
    },
    MuYaoSuiXinShouXieTi_Regular: {
        type: '5',
        code: 'muyaosuixinshouxieti',
        name: '沐瑶随心手写体',
        preview: 'images/font/muyaosuixinshouxieti/font.svg',
        posters: ['images/font/muyaosuixinshouxieti/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://www.zcool.com.cn/work/ZMzYwMzk2MjA=.html',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E6%B2%90%E7%91%B6%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E6%B2%90%E7%91%B6%E9%9A%8F%E5%BF%83%E6%89%8B%E5%86%99%E4%BD%93.ttf',
        desc: '「沐瑶随心手写体」站酷设计师@春颜秋色免费开发的第二款公益字体。沐瑶是以其女儿的名字命名的。字体本身是基于GB2312-80标准，共包含6763个汉字和数百个符号。'
    },
    BaoTuXiaoBaiTi_Regular: {
        type: '4',
        code: 'baotuxiaobaiti',
        name: '包图小白体',
        preview: 'images/font/baotuxiaobaiti/font.svg',
        posters: ['images/font/baotuxiaobaiti/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://act.ibaotu.com/activity/1.html',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E5%85%B6%E4%BB%96%E5%AD%97%E4%BD%93/%E5%8C%85%E5%9B%BE%E5%B0%8F%E7%99%BD%E4%BD%93.ttf',
        desc: '「包图小白体」定义为一款简单可爱的创意字体。在字形笔画上去除了折笔的弧形，换之以平直的笔画，竖弯钩转为竖折，同时弱化了钩笔画，省去了许多笔画末尾的小尾巴，显得更加直白可爱。粗短的笔画，像柯基的小短腿，相比细长的字体能给人更多的轻松感。整体形态采用了镂空的制作技巧，增强了字体的立体感，适合用于品牌标志、海报、包装、影视综艺、游戏、漫画等场景。包图小白体采用GB2312编码，共收容7707个字符，包含6763个简体汉字、110个大写字母、139个小写字母、102个数字、95个标点符号、其他特殊类符号288个、其他字母210个（包含日文平假名片假名）。'
    },
    JiangXiZhuoKai_Regular: {
        type: '4',
        code: 'jiangxizhuokai',
        name: '江西拙楷',
        preview: 'images/font/jiangxizhuokai/font.svg',
        posters: ['images/font/jiangxizhuokai/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://www.zcool.com.cn/work/ZNDE4MzY4Mjg=.html',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E5%85%B6%E4%BB%96%E5%AD%97%E4%BD%93/%E6%B1%9F%E8%A5%BF%E6%8B%99%E6%A5%B7.ttf',
        desc: '「江西拙楷」由站酷设计师@Fontree （黄煜臣）个人开发并发布，这是一套手写楷体，相比电脑中标准化制作的楷体，这套字体的笔画会带有一些书写的痕迹，每个字的笔画是没有统一标准的，所以看上去显得不够规范，但是会有一种手写的自然之感。'
    },
    WenCangShuFang_Regular: {
        type: '4',
        code: 'wencangshufang',
        name: '问藏书房',
        preview: 'images/font/wencangshufang/font.svg',
        posters: ['images/font/wencangshufang/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://www.wencang.com/font.jsp',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E5%85%B6%E4%BB%96%E5%AD%97%E4%BD%93/%E9%97%AE%E8%97%8F%E4%B9%A6%E6%88%BF.ttf',
        desc: '「问藏书房」字体是由问藏书房联合造字工房一起的设计的一款免费字体，字体整体现代简约，中宫紧凑，视觉阅读极具层次感，字字俊秀且呈现古雅之风，设计团队以精心的设计赋予了汉字全新美感！字符编码采用中华人民共和国GB2312-80字符集标准，按需添加101个汉字。共收容字数6864CJK汉字，ASCII常用字符100个。'
    },
    LianMengQiYiLuShuaiZhenRuiHeiTi_Regular: {
        type: '4',
        code: 'lianmengqiyilushuaizhenruiheiti',
        name: '联盟起艺卢帅正锐黑体',
        preview: 'images/font/lianmengqiyilushuaizhenruiheiti/font.svg',
        posters: ['images/font/lianmengqiyilushuaizhenruiheiti/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://www.zcool.com.cn/work/ZMzUxMzUzNzY=.html',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E5%85%B6%E4%BB%96%E5%AD%97%E4%BD%93/%E8%81%94%E7%9B%9F%E8%B5%B7%E8%89%BA%E5%8D%A2%E5%B8%85%E6%AD%A3%E9%94%90%E9%BB%91%E4%BD%93.ttf',
        desc: '「联盟起艺卢帅正锐黑体」由站酷设计师@设计师卢帅 在站酷发布，共计8000余字'
    },
    XianErTi_Regular: {
        type: '4',
        code: 'xianerti',
        name: '贤二体',
        preview: 'images/font/xianerti/font.svg',
        posters: ['images/font/xianerti/poster.svg'],
        license: '商免',
        auth: true,
        source: 'https://www.zcool.com.cn/article/ZNjk4NDM2.html',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E5%85%B6%E4%BB%96%E5%AD%97%E4%BD%93/%E8%B4%A4%E4%BA%8C%E4%BD%93.ttf',
        desc: '「贤二体」是龙泉专寺动漫中心与汉仪字库联合推出的一款免费商用字体。贤二体的字形偏长，起笔收笔锋利且粗细对比明显，笔画笨拙微带曲线感。字体组合结构松散，重心不稳，达到诙谐幽默，惹人喜爱的效果。'
    },
    ShouShuTi_Regular: {
        type: '5',
        code: 'shoushuti',
        name: '手书体',
        preview: 'images/font/shoushuti/font.svg',
        posters: ['images/font/shoushuti/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://www.zcool.com.cn/work/ZMjI2MDk1MDg=.html',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E5%85%B6%E4%BB%96%E5%AD%97%E4%BD%93/%E6%89%8B%E4%B9%A6%E4%BD%93.ttf',
        desc: '由站酷设计师@Joker9 设计，收录基本汉字6763个，字体风格为手写风格，可以用于slogan、banner、海报、商标等设计里面。'
    },
    YangRenDongZhuShiTi_Regular: {
        type: '4',
        code: 'yangrendongzhushiti',
        name: '杨任东竹石体',
        preview: 'images/font/yangrendongzhushiti/font.svg',
        posters: ['images/font/yangrendongzhushiti/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://mp.weixin.qq.com/s/7kv3i_YEs7x9_9IrCDYvBA',
        download: '',
        desc: '杨任东竹石体于2017年4月26日世界知识产权日正式发布，本字体版本为1.23字体按照GB2312-80书写，并增补了少量常见汉字；整套字体有7个字重，共计50000余个字符'
    },
    ZiTiShiJieFaGunTi_Regular: {
        type: '4',
        code: 'zitishijiefagunti',
        name: '字体视界法棍体',
        preview: 'images/font/zitishijiefagunti/font.svg',
        posters: ['images/font/zitishijiefagunti/poster.svg'],
        license: '商免',
        auth: true,
        source: 'https://www.17font.com/fontDay/OpenSource',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E5%85%B6%E4%BB%96%E5%AD%97%E4%BD%93/%E5%AD%97%E4%BD%93%E8%A7%86%E7%95%8C%E6%B3%95%E6%A3%8D%E4%BD%93.ttf',
        desc: '「字体视界法棍体」由原字体（《义启嘟嘟体》登记号：沪作登字-2016-F-00712739）更名而来。由上海义启信息科技有限公司字库部员工通过字体软件进行设计与制作，为了让更多的人可以免费使用商用字体，公司决定改名为《字体视界法棍体》，并于2019年7月17日字体节这天在字体视界官网发布许可广大用户免费商用。字体视界法棍体笔画中间呈弧形外拓，充满张力，加粗字形笔画显得更可爱个性；结构空间变化不像正体那样小，以拙为巧，憨态可掬。这款字体笔画纤细充满张力，规律加粗，曲线折角充分展现它可爱不粗笨的气质笔画，结构外圆内疏，左右呼应如手写，各个字生机勃勃又融为一体，整体一气呵成。采用 GB2312 编码，共收容 7698 个字符，包含 6771 个汉字，110 个大写字母，139 个小写字母，102 个数字（包含阿拉伯数字，罗马数字等），98 个标点符号，其他特殊符号 164 个，其他字母 224 个。'
    },
    ZhuoJianGanLanJianTi_Regular: {
        type: '4',
        code: 'zhuojianganlanjianti',
        name: '卓健橄榄简体',
        preview: 'images/font/zhuojianganlanjianti/font.svg',
        posters: ['images/font/zhuojianganlanjianti/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://www.zcool.com.cn/work/ZNDA2MzA3ODQ=.html',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E5%85%B6%E4%BB%96%E5%AD%97%E4%BD%93/%E5%8D%93%E5%81%A5%E6%A9%84%E6%A6%84%E7%AE%80%E4%BD%93.ttf',
        desc: '「卓健橄榄简体」由卓米品牌设计发布，并于于2019年底授权限时免费商用。收容7050个常用字，52 个英文字母，139个阿拉伯数字及常用标点符号，卓健橄榄简体是一款相对较时尚的字体，部分笔画斜切处理，让字体更具时尚感和时尚属性，整体中心偏上，更符合现代审美。官方给出的说法是限时免费下载，免费商用。具体是指可以免费商用，限时下载，还是限时免费商用，官方没有给出明确解释，这点存有疑问。如果有商用需求，请与官方联系求证。'
    },
    YouSheBiaoTiHei_Regular: {
        type: '4',
        code: 'youshebiaotihei',
        name: '优设标题黑',
        preview: 'images/font/youshebiaotihei/font.svg',
        posters: ['images/font/youshebiaotihei/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://www.uisdc.com/uisdc-first-free-font',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E5%85%B6%E4%BB%96%E5%AD%97%E4%BD%93/%E4%BC%98%E8%AE%BE%E6%A0%87%E9%A2%98%E9%BB%91.ttf',
        desc: '「优设标题黑」由优设与字由合作完成，是一款适用性广，速度感、力量感极强的专业美术标题字体。它以黑体字型为基础，整体字形沉稳，同时采用较大字面和粗壮的笔画来强化力量感。每个字体水平倾斜 8° 的设计，赋予了字体极强的速度感，为了让字体倾斜后也能保持稳固，设计师将整体字身设定宽扁。而起笔和弯钩上独具匠心的尖角设计，不仅突显了设计的几何感，而且方便后期修改。'
    },
    RuiZiZhenYanTi_Regular: {
        type: '4',
        code: 'ruizizhenyanti',
        name: '锐字真言体',
        preview: 'images/font/ruizizhenyanti/font.svg',
        posters: ['images/font/ruizizhenyanti/poster.svg'],
        license: '商免',
        auth: false,
        source: 'http://reeji.com/font/rui_zi_zhen_yan_ti/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E5%85%B6%E4%BB%96%E5%AD%97%E4%BD%93/%E9%94%90%E5%AD%97%E7%9C%9F%E8%A8%80%E4%BD%93.ttf',
        desc: '「锐字真言体」是锐字家族字体当中第一款免费可商用的字体。真言体笔触浑厚有力，笔画曲折有度，字形个性鲜明，刚柔并济，落笔简洁有序，给人以遒劲有力、端正凝练的感受。直角与圆角的错落搭配使得字体婉转有度，落落大方，具有自己独到的风格！这款字体特别适用于文字标题、竞技视觉、广告设计、个性品牌设计推广、企业宣传及时尚品牌的设计应用。'
    },
    XinYeNianTi_Regular: {
        type: '5',
        code: 'xinyenianti',
        name: '新叶念体',
        preview: 'images/font/xinyenianti/font.svg',
        posters: ['images/font/xinyenianti/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://www.zcool.com.cn/work/ZMzc1MDI2Njg=.html',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E5%85%B6%E4%BB%96%E5%AD%97%E4%BD%93/%E6%96%B0%E5%8F%B6%E5%BF%B5%E4%BD%93.otf',
        desc: '「新叶念体」采用GB2312编码，约6900字，王亚设计 在站酷发布。'
    },
    QingSongShouXieTiYi_Regular: {
        type: '5',
        code: 'qingsongshouxietiyi',
        name: '清松手写体1',
        preview: 'images/font/qingsongshouxietiyi/font.svg',
        posters: ['images/font/qingsongshouxietiyi/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://www.facebook.com/groups/549661292148791/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E5%85%B6%E4%BB%96%E5%AD%97%E4%BD%93/%E6%B8%85%E6%9D%BE%E6%89%8B%E5%AF%AB%E9%AB%94/%E6%B8%85%E6%9D%BE%E6%89%8B%E5%AF%AB%E9%AB%941.ttf',
        desc: '「清松手写体」它是一款来自台湾的字体，它由游清松建立，为了创建这个字体，他还成立了一个小组： 「顺其字然」，首先先在稿纸上用原子笔手写，然后，透过「守写字」网站产生出初稿字体，再透过字体软件后制加工的手写字体。「顺其字然」手写字体，没有一般计算机字型的生硬感，多了几分手写般的自然感。不论是中文、英文、符号数字，适合在计算机屏幕上阅读、排版，打印出来效果也很棒的！'
    },
    QingSongShouXieTiEr_Regular: {
        type: '5',
        code: 'qingsongshouxietier',
        name: '清松手写体2',
        preview: 'images/font/qingsongshouxietier/font.svg',
        posters: ['images/font/qingsongshouxietier/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://www.facebook.com/groups/549661292148791/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E5%85%B6%E4%BB%96%E5%AD%97%E4%BD%93/%E6%B8%85%E6%9D%BE%E6%89%8B%E5%AF%AB%E9%AB%94/%E6%B8%85%E6%9D%BE%E6%89%8B%E5%AF%AB%E9%AB%942.ttf',
        desc: '「清松手写体」它是一款来自台湾的字体，它由游清松建立，为了创建这个字体，他还成立了一个小组： 「顺其字然」，首先先在稿纸上用原子笔手写，然后，透过「守写字」网站产生出初稿字体，再透过字体软件后制加工的手写字体。「顺其字然」手写字体，没有一般计算机字型的生硬感，多了几分手写般的自然感。不论是中文、英文、符号数字，适合在计算机屏幕上阅读、排版，打印出来效果也很棒的！'
    },
    QingSongShouXieTiSan_Regular: {
        type: '5',
        code: 'qingsongshouxietisan',
        name: '清松手写体3',
        preview: 'images/font/qingsongshouxietisan/font.svg',
        posters: ['images/font/qingsongshouxietisan/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://www.facebook.com/groups/549661292148791/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E5%85%B6%E4%BB%96%E5%AD%97%E4%BD%93/%E6%B8%85%E6%9D%BE%E6%89%8B%E5%AF%AB%E9%AB%94/%E6%B8%85%E6%9D%BE%E6%89%8B%E5%AF%AB%E9%AB%943.ttf',
        desc: '「清松手写体」它是一款来自台湾的字体，它由游清松建立，为了创建这个字体，他还成立了一个小组： 「顺其字然」，首先先在稿纸上用原子笔手写，然后，透过「守写字」网站产生出初稿字体，再透过字体软件后制加工的手写字体。「顺其字然」手写字体，没有一般计算机字型的生硬感，多了几分手写般的自然感。不论是中文、英文、符号数字，适合在计算机屏幕上阅读、排版，打印出来效果也很棒的！'
    },
    FandolFang_Regular: {
        type: '2',
        code: 'fandolfang',
        name: '破产字体仿宋',
        preview: 'images/font/fandolfang/font.svg',
        posters: ['images/font/fandolfang/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://ctan.org/tex-archive/fonts/fandol',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%A0%B4%E4%BA%A7%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/FandolFang-Regular.otf',
        desc: '「破产字体」（Fandol）来自一家已经破产的字体公司，现在已经开源了。包含FandolFang、FandolHei、FandolKai、FandolSong四个字体。'
    },
    FandolHei_Regular: {
        type: '1',
        code: 'fandolhei',
        name: '破产字体黑体',
        preview: 'images/font/fandolhei/font.svg',
        posters: ['images/font/fandolhei/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://ctan.org/tex-archive/fonts/fandol',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%A0%B4%E4%BA%A7%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/FandolHei-Regular.otf',
        desc: '「破产字体」（Fandol）来自一家已经破产的字体公司，现在已经开源了。包含FandolFang、FandolHei、FandolKai、FandolSong四个字体。'
    },
    FandolKai_Regular: {
        type: '3',
        code: 'fandolkai',
        name: '破产字体楷体',
        preview: 'images/font/fandolkai/font.svg',
        posters: ['images/font/fandolkai/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://ctan.org/tex-archive/fonts/fandol',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%A0%B4%E4%BA%A7%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/FandolKai-Regular.otf',
        desc: '「破产字体」（Fandol）来自一家已经破产的字体公司，现在已经开源了。包含FandolFang、FandolHei、FandolKai、FandolSong四个字体。'
    },
    FandolSong_Regular: {
        type: '2',
        code: 'fandolsong',
        name: '破产字体宋体',
        preview: 'images/font/fandolsong/font.svg',
        posters: ['images/font/fandolsong/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://ctan.org/tex-archive/fonts/fandol',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%A0%B4%E4%BA%A7%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/FandolSong-Regular.otf',
        desc: '「破产字体」（Fandol）来自一家已经破产的字体公司，现在已经开源了。包含FandolFang、FandolHei、FandolKai、FandolSong四个字体。'
    },
    OPPOSans_Regular: {
        type: '1',
        code: 'opposans',
        name: 'OPPO Sans 字体',
        preview: 'images/font/opposans/font.svg',
        posters: ['images/font/opposans/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://bbs.coloros.net/graphic?id=2272309',
        download: 'https://github.com/wordshub/free-font/tree/master/assets/font/%E4%B8%AD%E6%96%87/%E5%85%B6%E4%BB%96%E5%AD%97%E4%BD%93/OPPO%20Sans',
        desc: '「OPPO Sans」 是 OPPO 全新品牌字体，首发于 ColorOS 6 操作系统，由 OPPO 与国内知名字体厂商汉仪合作开发出的全新中文字库，总共 226003 个字节。OPPO Sans 紧随品牌升级的步调，用文字全方位探索科技美感，字体整体简洁优雅，字型设计富有现代感，极具科技美感。字体采用全新骨架设计，中宫自然舒适，更加挺拔优雅；同时简化笔画，把握更多细节处理，去除出脚，使字体显得更加干净。简洁富有变化的字体线条还融入 OPPO 产品曲线美学，极具现代感和未来感，字体更加现代，笔画更加均匀，视觉表现更加整洁，非常适合用来作为设计素材使用，实用性相当广泛。'
    },
    CwTeXQMing_Regular: {
        type: '2',
        code: 'cwtexqming',
        name: 'cwTeX 中明體',
        preview: 'images/font/cwtexqming/font.svg',
        posters: ['images/font/cwtexqming/poster.svg'],
        license: 'OFL-1.1',
        auth: false,
        source: 'https://github.com/l10n-tw/cwtex-q-fonts',
        download: 'https://github.com/l10n-tw/cwtex-q-fonts-TTFs/archive/v0.4.zip',
        desc: '「cwTeX 字体」最初是由 Tsong-Min Wu 及 Tsong-Huey Wu 于 1999 至 2004 年间制作作并以 GNU GENERAL PUBLIC LICENSE Version 2 or latter 发布。于 2014 年，Tsong-Min Wu、Tsong-Huey Wu、Edward G.J. Lee 及 Chen-Pan Liao 四人同意将汉字及中文常用标点符号之字符另外独立并以 SIL Open Font License (Version 1.1) 授出，以利与其他 OFL 授权之字体整合。'
    },
    CwTeXQKai_Regular: {
        type: '3',
        code: 'cwtexqkai',
        name: 'cwTeX 中楷體',
        preview: 'images/font/cwtexqkai/font.svg',
        posters: ['images/font/cwtexqkai/poster.svg'],
        license: 'OFL-1.1',
        auth: false,
        source: 'https://github.com/l10n-tw/cwtex-q-fonts',
        download: 'https://github.com/l10n-tw/cwtex-q-fonts-TTFs/archive/v0.4.zip',
        desc: '「cwTeX 字体」最初是由 Tsong-Min Wu 及 Tsong-Huey Wu 于 1999 至 2004 年间制作作并以 GNU GENERAL PUBLIC LICENSE Version 2 or latter 发布。于 2014 年，Tsong-Min Wu、Tsong-Huey Wu、Edward G.J. Lee 及 Chen-Pan Liao 四人同意将汉字及中文常用标点符号之字符另外独立并以 SIL Open Font License (Version 1.1) 授出，以利与其他 OFL 授权之字体整合。'
    },
    CwTeXQHei_Regular: {
        type: '1',
        code: 'cwtexqhei',
        name: 'cwTeX 粗黑體',
        preview: 'images/font/cwtexqhei/font.svg',
        posters: ['images/font/cwtexqhei/poster.svg'],
        license: 'OFL-1.1',
        auth: false,
        source: 'https://github.com/l10n-tw/cwtex-q-fonts',
        download: 'https://github.com/l10n-tw/cwtex-q-fonts-TTFs/archive/v0.4.zip',
        desc: '「cwTeX 字体」最初是由 Tsong-Min Wu 及 Tsong-Huey Wu 于 1999 至 2004 年间制作作并以 GNU GENERAL PUBLIC LICENSE Version 2 or latter 发布。于 2014 年，Tsong-Min Wu、Tsong-Huey Wu、Edward G.J. Lee 及 Chen-Pan Liao 四人同意将汉字及中文常用标点符号之字符另外独立并以 SIL Open Font License (Version 1.1) 授出，以利与其他 OFL 授权之字体整合。'
    },
    CwTeXQYuan_Regular: {
        type: '4',
        code: 'cwtexqyuan',
        name: 'cwTeX 中圆體',
        preview: 'images/font/cwtexqyuan/font.svg',
        posters: ['images/font/cwtexqyuan/poster.svg'],
        license: 'OFL-1.1',
        auth: false,
        source: 'https://github.com/l10n-tw/cwtex-q-fonts',
        download: 'https://github.com/l10n-tw/cwtex-q-fonts-TTFs/archive/v0.4.zip',
        desc: '「cwTeX 字体」最初是由 Tsong-Min Wu 及 Tsong-Huey Wu 于 1999 至 2004 年间制作作并以 GNU GENERAL PUBLIC LICENSE Version 2 or latter 发布。于 2014 年，Tsong-Min Wu、Tsong-Huey Wu、Edward G.J. Lee 及 Chen-Pan Liao 四人同意将汉字及中文常用标点符号之字符另外独立并以 SIL Open Font License (Version 1.1) 授出，以利与其他 OFL 授权之字体整合。'
    },
    CwTeXQFangSong_Regular: {
        type: '2',
        code: 'cwtexqfangsong',
        name: 'cwTeX 中仿宋體',
        preview: 'images/font/cwtexqfangsong/font.svg',
        posters: ['images/font/cwtexqfangsong/poster.svg'],
        license: 'OFL-1.1',
        auth: false,
        source: 'https://github.com/l10n-tw/cwtex-q-fonts',
        download: 'https://github.com/l10n-tw/cwtex-q-fonts-TTFs/archive/v0.4.zip',
        desc: '「cwTeX 字体」最初是由 Tsong-Min Wu 及 Tsong-Huey Wu 于 1999 至 2004 年间制作作并以 GNU GENERAL PUBLIC LICENSE Version 2 or latter 发布。于 2014 年，Tsong-Min Wu、Tsong-Huey Wu、Edward G.J. Lee 及 Chen-Pan Liao 四人同意将汉字及中文常用标点符号之字符另外独立并以 SIL Open Font License (Version 1.1) 授出，以利与其他 OFL 授权之字体整合。'
    },
    YiDianYanTi_Regular: {
        type: '4',
        code: 'yidianyanti',
        name: '一点颜体',
        preview: 'images/font/yidianyanti/font.svg',
        posters: ['images/font/yidianyanti/poster.svg'],
        license: 'GPL-3.0',
        auth: false,
        source: 'http://founder.acgvlyric.org/iu/doku.php/%E9%80%A0%E5%AD%97:%E9%96%8B%E6%BA%90%E5%AD%97%E5%9E%8B_i.%E9%A1%8F%E9%AB%94',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E5%88%BB%E7%9F%B3%E5%BD%95%E7%B3%BB%E5%88%97/I.%E9%A1%8F%E9%AB%94.ttf',
        desc: '「一点颜体」是由王汉宗颜体修改而来，重新制作和修整原字型中缺少的或有欠美观的部份，例如全半形英数、平假名、片假名、拉丁字母、俄文字母、阿拉伯数字、圈圈字、常用符号等。'
    },
    YiDianGangBiHeTi_Regular: {
        type: '4',
        code: 'yidiangangbiheti',
        name: '一点钢笔鹤体',
        preview: 'images/font/yidiangangbiheti/font.svg',
        posters: ['images/font/yidiangangbiheti/poster.svg'],
        license: 'GPL-3.0',
        auth: false,
        source: 'http://founder.acgvlyric.org/iu/doku.php/%E9%80%A0%E5%AD%97:%E9%96%8B%E6%BA%90%E5%AD%97%E5%9E%8B_i.%E9%8B%BC%E7%AD%86%E9%B6%B4%E9%AB%94',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E5%88%BB%E7%9F%B3%E5%BD%95%E7%B3%BB%E5%88%97/I.%E9%8B%BC%E7%AD%86%E9%B6%B4%E9%AB%94.ttf',
        desc: '「一点钢笔鹤体」由王汉宗粗钢体修改而来，刻石錄重新制作和修整原字型中缺少的或有欠美观的部份，例如半形英数、圈圈字、常用符号等。'
    },
    YiDianMingTi_Regular: {
        type: '2',
        code: 'yidianmingti',
        name: '一点明体',
        preview: 'images/font/yidianmingti/font.svg',
        posters: ['images/font/yidianmingti/poster.svg'],
        license: 'IPA-1.0',
        auth: false,
        source: 'http://founder.acgvlyric.org/iu/doku.php/%E9%80%A0%E5%AD%97:%E9%96%8B%E6%BA%90%E5%AD%97%E5%9E%8B_i.%E6%98%8E%E9%AB%94',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E5%88%BB%E7%9F%B3%E5%BD%95%E7%B3%BB%E5%88%97/I.%E6%98%8E%E9%AB%94.ttf',
        desc: '「一点明体」是一套依照传承字形标准化文件《传承字形部件检校表》的推荐字形标准，并以 TrueType格式封装、依照 Unicode 编码的 OpenType字型。I.明体 名称里的 I 是罗马数字 一，I. 念作 一点，象徵笔画的基本：点与线。目前I.明体已由开源字型组织一点字坊 全力维护。'
    },
    WenQuanYiZhengHei_Regular: {
        type: '1',
        code: 'wenquanyizhenghei',
        name: '文泉驿正黑',
        preview: 'images/font/wenquanyizhenghei/font.svg',
        posters: ['images/font/wenquanyizhenghei/poster.svg'],
        license: 'GPL-2.0',
        auth: false,
        source: 'http://wenq.org/wqy2/index.cgi?ZenHei',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E5%88%BB%E7%9F%B3%E5%BD%95%E7%B3%BB%E5%88%97/I.%E6%98%8E%E9%AB%94.ttf',
        desc: '「文泉驿正黑体」是一个"自由字体"。该字体包含了所有常用简体中文、繁体中文所需要的汉字(最新版本包含超过27842个汉字，完整覆盖GB2312/Big5/GBK以及GB18030标准字符集)。该字体同时还包含了日文、韩文和其他几十种语言符号。除此以外，该字体还嵌入了最新版本的文泉驿点阵宋体的中英文点阵，使得屏幕汉字显示清晰锐利，易于阅读。作为黑体中文字体，文泉驿正黑为非衬线字体，笔画对比度明显，特别适合屏幕汉字显示以及文档标题字体。'
    },
    WenQuanYiWeiMiHei_Regular: {
        type: '1',
        code: 'wenquanyiweimihei',
        name: '文泉驿微米黑',
        preview: 'images/font/wenquanyiweimihei/font.svg',
        posters: ['images/font/wenquanyiweimihei/poster.svg'],
        license: 'GPL-2.0',
        auth: false,
        source: 'http://wenq.org/wqy2/index.cgi?MicroHei',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E5%88%BB%E7%9F%B3%E5%BD%95%E7%B3%BB%E5%88%97/I.%E6%98%8E%E9%AB%94.ttf',
        desc: '「文泉驿微米黑」是一个"自由字体"。该字体包含了所有常用简体中文、繁体中文所需要的汉字(最新版本包含超过20932个汉字，完整覆盖GB2312/Big5以及GBK标准字符集)。该字体同时还包含了日文、韩文和其他几十种语言符号。以外，该字体还包含了高质量的Droid Sans拉丁符号和Droid Sans Mono等宽字体，并内置Hinting和Kerning信息。微米黑字体文件极小，特别使用于便携式电脑设备。 该字体版权受到法律保护，字体版权人为Google和文泉驿信任委员会。请遵循官方字体授权使用并衍生本字体'
    },
    HanaMin_Regular: {
        type: '2',
        code: 'hanamin',
        name: '花园明朝',
        preview: 'images/font/hanamin/font.svg',
        posters: ['images/font/hanamin/poster.svg'],
        license: 'OFL-1.1',
        auth: false,
        source: 'http://fonts.jp/hanazono/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E6%97%A5%E6%96%87/%E8%8A%B1%E5%9B%AD%E6%98%8E%E6%9C%9D/HanaMinA.ttf',
        desc: '「花园明朝体」（HanaMin 花园フォント）是一款基于日语的自由开源汉字字体。这款字体的特点是涵盖了目前 CJK (中日韩统一表意文字)字库中几乎所有的汉字与字符，而且作为开源项目，任何人可自由下载使用。如果在软件中找不到此字体，请查找名称：HanaMin。此字体对简体中文支持比较好。'
    },
    YuanJieMingChaoTi_Regular: {
        type: '2',
        code: 'yuanjiemingchaoti',
        name: '源界明朝体',
        preview: 'images/font/yuanjiemingchaoti/font.svg',
        posters: ['images/font/yuanjiemingchaoti/poster.svg'],
        license: 'OFL-1.1',
        auth: false,
        source: 'https://flopdesign.com/blog/font/5146/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E6%97%A5%E6%96%87/%E6%BA%90%E7%95%8C%E6%98%8E%E6%9C%9D%E4%BD%93.ttf',
        desc: '「源界明朝体」这款字体是以「思源宋体」（日文为「源ノ明朝」）为基础，加入破坏效果使其最接近可读状态，可以简单理解成思源宋体的破坏版，源界明朝在视觉上具有相当大的张力，可作为图片内的标题和大字使用，整体来说相当吸睛且颇具效果。源界明朝体为日文字体，对部分简体中文支持不太好。'
    },
    SoukouMincho_Regular: {
        type: '2',
        code: 'soukoumincho',
        name: '装甲明朝',
        preview: 'images/font/soukoumincho/font.svg',
        posters: ['images/font/soukoumincho/poster.svg'],
        license: 'OFL-1.1',
        auth: false,
        source: 'http://flopdesign.com/blog/font/5228/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E6%97%A5%E6%96%87/%E8%A3%85%E7%94%B2%E6%98%8E%E6%9C%9D%E4%BD%93.ttf',
        desc: '「装甲明朝」是日本网友以思源宋体为基础，修改后开放免费下载的新字型。字体风格硬朗有气派，若是拿来做越野车、大型装甲机车等玩具淘宝海报设计就非常适用了。Soukou Mincho 装甲明朝体支持繁体（分部）、简体（部分）、英文、日文以及数字符号。'
    },
    GenWan_Regular: {
        type: '2',
        code: 'genwan',
        name: '源云明体',
        preview: 'images/font/genwan/font.svg',
        posters: ['images/font/genwan/poster.svg'],
        license: 'OFL-1.1',
        auth: false,
        source: 'https://github.com/ButTaiwan/genwan-font',
        download: 'https://github.com/ButTaiwan/genwan-font',
        desc: '「源云明体」是基于思源宋体的而改造的开放原始码中文字型。源云明体在横笔的起笔及竖笔的起笔、收笔处加入粗细变化，笔画交叉处有朦胧处理。'
    },
    GenRyu_Regular: {
        type: '2',
        code: 'genryu',
        name: '源流明体',
        preview: 'images/font/genryu/font.svg',
        posters: ['images/font/genryu/poster.svg'],
        license: 'OFL-1.1',
        auth: false,
        source: 'https://github.com/ButTaiwan/genryu-font',
        download: 'https://github.com/ButTaiwan/genryu-font',
        desc: '「源流明体」是基于思源宋体的而改造的开放原始码中文字型。源流明体在笔画上有所调整，使字型看起来更有力道'
    },
    GenYo_Regular: {
        type: '2',
        code: 'genyo',
        name: '源样明体',
        preview: 'images/font/genyo/font.svg',
        posters: ['images/font/genyo/poster.svg'],
        license: 'OFL-1.1',
        auth: false,
        source: 'https://github.com/ButTaiwan/genyo-font',
        download: 'https://github.com/ButTaiwan/genyo-font',
        desc: '「源样明体」是基于思源宋体的开放原始码中文字型。 採用思源宋体韩文（KR）版本的字符，配合繁体中文惯用的置中标点，可排版传统印刷体风格的文件。源样明体采用思源宋体韩文版本的字符，配合繁体中文习惯的置中标点符号，可说是兼具排版及传统印刷体风格的繁体中文字体'
    },
    Seto_Regular: {
        type: '4',
        code: 'seto',
        name: '濑户体',
        preview: 'images/font/seto/font.svg',
        posters: ['images/font/seto/poster.svg'],
        license: 'OFL-1.1',
        auth: false,
        source: 'http://setofont.osdn.jp/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E6%97%A5%E6%96%87/%E6%BF%91%E6%88%B7%E4%BD%93.ttf',
        desc: '「濑户字体」是一款偏可爱风的字体，支持简体中文、繁体中文、日文，包含CJK常用汉字、平片假名、JIS第一至四级，共30000余字。这是由日本的一位业余字体设计师濑户のぞみ小姐所制作的。'
    },
    ShouXieZaZiTi_Regular: {
        type: '5',
        code: 'shouxiezaziti',
        name: '手写杂字体',
        preview: 'images/font/shouxiezaziti/font.svg',
        posters: ['images/font/shouxiezaziti/poster.svg'],
        license: '商免',
        auth: false,
        source: 'http://setofont.osdn.jp/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E6%97%A5%E6%96%87/851%E6%89%8B%E5%86%99%E6%9D%82%E5%AD%97%E4%BD%93.ttf',
        desc: '「手写杂字体」这是一个日本人制作的一款有点可爱风格的字体，所以会是日本字形（然而作者表示其实日本标准很多地方他都没遵循，所以叫杂字体）。作者的描述是自由使用与重新配布，可商用，但是保留著作权，字体仍在不断更新加字中。此款手写杂字体，虽为日文字体，但对中文繁体以及中文简体都支持得灰常不错。'
    },
    StanukiPermanentMarker_Regular: {
        type: '5',
        code: 'tanukipermanentmarker',
        name: '麦克笔手绘体',
        preview: 'images/font/tanukipermanentmarker/font.svg',
        posters: ['images/font/tanukipermanentmarker/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://tanukifont.com/tanuki-permanent-marker/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E6%97%A5%E6%96%87/%E9%BA%A6%E5%85%8B%E7%AC%94%E6%89%8B%E7%BB%98%E4%BD%93.ttf',
        desc: '「麦克笔手绘体」一款日本网站提供的免费商用字体，たぬき油性マジック(TanukiMagic) 字型风格和马克笔手绘的 POP 效果如出一辙。'
    },
    WangHanZongChaoHeiQiaoPiDongWu_Regular: {
        type: '4',
        code: 'wanghanzongchaoheiqiaopidongwu',
        name: '王漢宗超黑體俏皮動物',
        preview: 'images/font/wanghanzongchaoheiqiaopidongwu/font.svg',
        posters: ['images/font/wanghanzongchaoheiqiaopidongwu/poster.svg'],
        license: 'GPL-2.0',
        auth: false,
        source: 'https://code.google.com/archive/p/wangfonts/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%8E%8B%E6%B1%89%E5%AE%97%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%8E%8B%E6%BC%A2%E5%AE%97%E8%B6%85%E9%BB%91%E9%AB%94%E4%BF%8F%E7%9A%AE%E5%8B%95%E7%89%A9%E4%B8%80.ttf',
        desc: '「王汉宗自由字型」由研发天蚕字库的台湾中原大学数学系王汉宗教授先分别在2000年和2004年先后捐出十套WCL系列字型和32套新字型，全部以GNU GPL许可分发。'
    },
    WangHanZongChaoMingTiFan_Regular: {
        type: '2',
        code: 'wanghanzongchaomingtifan',
        name: '王漢宗超明體繁',
        preview: 'images/font/wanghanzongchaomingtifan/font.svg',
        posters: ['images/font/wanghanzongchaomingtifan/poster.svg'],
        license: 'GPL-2.0',
        auth: false,
        source: 'https://code.google.com/archive/p/wangfonts/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%8E%8B%E6%B1%89%E5%AE%97%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%8E%8B%E6%BC%A2%E5%AE%97%E8%B6%85%E6%98%8E%E9%AB%94%E7%B9%81.ttf',
        desc: '「王汉宗自由字型」由研发天蚕字库的台湾中原大学数学系王汉宗教授先分别在2000年和2004年先后捐出十套WCL系列字型和32套新字型，全部以GNU GPL许可分发。'
    },
    WangHanZongCuKaiTiJian_Regular: {
        type: '3',
        code: 'wanghanzongcukaitijian',
        name: '王漢宗粗楷體簡',
        preview: 'images/font/wanghanzongcukaitijian/font.svg',
        posters: ['images/font/wanghanzongcukaitijian/poster.svg'],
        license: 'GPL-2.0',
        auth: false,
        source: 'https://code.google.com/archive/p/wangfonts/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%8E%8B%E6%B1%89%E5%AE%97%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%8E%8B%E6%BC%A2%E5%AE%97%E7%B2%97%E6%A5%B7%E9%AB%94%E7%B0%A1.ttf',
        desc: '「王汉宗自由字型」由研发天蚕字库的台湾中原大学数学系王汉宗教授先分别在2000年和2004年先后捐出十套WCL系列字型和32套新字型，全部以GNU GPL许可分发。'
    },
    WangHanZongCuMingTiFan_Regular: {
        type: '2',
        code: 'wanghanzongcumingtifan',
        name: '王漢宗粗明體繁',
        preview: 'images/font/wanghanzongcumingtifan/font.svg',
        posters: ['images/font/wanghanzongcumingtifan/poster.svg'],
        license: 'GPL-2.0',
        auth: false,
        source: 'https://code.google.com/archive/p/wangfonts/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%8E%8B%E6%B1%89%E5%AE%97%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%8E%8B%E6%BC%A2%E5%AE%97%E7%B2%97%E6%98%8E%E9%AB%94%E7%B9%81.ttf',
        desc: '「王汉宗自由字型」由研发天蚕字库的台湾中原大学数学系王汉宗教授先分别在2000年和2004年先后捐出十套WCL系列字型和32套新字型，全部以GNU GPL许可分发。'
    },
    WangHanZongGanBiXingKaiFan_Regular: {
        type: '3',
        code: 'wanghanzonggangbixingkaifan',
        name: '王漢宗鋼筆行楷繁',
        preview: 'images/font/wanghanzonggangbixingkaifan/font.svg',
        posters: ['images/font/wanghanzonggangbixingkaifan/poster.svg'],
        license: 'GPL-2.0',
        auth: false,
        source: 'https://code.google.com/archive/p/wangfonts/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%8E%8B%E6%B1%89%E5%AE%97%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%8E%8B%E6%BC%A2%E5%AE%97%E9%8B%BC%E7%AD%86%E8%A1%8C%E6%A5%B7%E7%B9%81.ttf',
        desc: '「王汉宗自由字型」由研发天蚕字库的台湾中原大学数学系王汉宗教授先分别在2000年和2004年先后捐出十套WCL系列字型和32套新字型，全部以GNU GPL许可分发。'
    },
    WangHanZongKongDieLiuFan_Regular: {
        type: '4',
        code: 'wanghanzongkongdieliufan',
        name: '王漢宗空疊圓繁',
        preview: 'images/font/wanghanzongkongdieliufan/font.svg',
        posters: ['images/font/wanghanzongkongdieliufan/poster.svg'],
        license: 'GPL-2.0',
        auth: false,
        source: 'https://code.google.com/archive/p/wangfonts/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%8E%8B%E6%B1%89%E5%AE%97%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%8E%8B%E6%BC%A2%E5%AE%97%E7%A9%BA%E7%96%8A%E5%9C%93%E7%B9%81.ttf',
        desc: '「王汉宗自由字型」由研发天蚕字库的台湾中原大学数学系王汉宗教授先分别在2000年和2004年先后捐出十套WCL系列字型和32套新字型，全部以GNU GPL许可分发。'
    },
    WangHanZongKuLiHaiBao_Regular: {
        type: '4',
        code: 'wanghanzongkulihaibao',
        name: '王漢宗酷儷海報',
        preview: 'images/font/wanghanzongkulihaibao/font.svg',
        posters: ['images/font/wanghanzongkulihaibao/poster.svg'],
        license: 'GPL-2.0',
        auth: false,
        source: 'https://code.google.com/archive/p/wangfonts/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%8E%8B%E6%B1%89%E5%AE%97%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%8E%8B%E6%BC%A2%E5%AE%97%E9%85%B7%E5%84%B7%E6%B5%B7%E5%A0%B1.ttf',
        desc: '「王汉宗自由字型」由研发天蚕字库的台湾中原大学数学系王汉宗教授先分别在2000年和2004年先后捐出十套WCL系列字型和32套新字型，全部以GNU GPL许可分发。'
    },
    WangHanZongKuZhengHaiBao_Regular: {
        type: '4',
        code: 'wanghanzongkuzhenghaibao',
        name: '王漢宗酷正海報',
        preview: 'images/font/wanghanzongkuzhenghaibao/font.svg',
        posters: ['images/font/wanghanzongkuzhenghaibao/poster.svg'],
        license: 'GPL-2.0',
        auth: false,
        source: 'https://code.google.com/archive/p/wangfonts/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%8E%8B%E6%B1%89%E5%AE%97%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%8E%8B%E6%BC%A2%E5%AE%97%E9%85%B7%E6%AD%A3%E6%B5%B7%E5%A0%B1.ttf',
        desc: '「王汉宗自由字型」由研发天蚕字库的台湾中原大学数学系王汉宗教授先分别在2000年和2004年先后捐出十套WCL系列字型和32套新字型，全部以GNU GPL许可分发。'
    },
    WangHanZongTeHeiTiFan_Regular: {
        type: '1',
        code: 'wanghanzongteheitifan',
        name: '王漢宗特黑體繁',
        preview: 'images/font/wanghanzongteheitifan/font.svg',
        posters: ['images/font/wanghanzongteheitifan/poster.svg'],
        license: 'GPL-2.0',
        auth: false,
        source: 'https://code.google.com/archive/p/wangfonts/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%8E%8B%E6%B1%89%E5%AE%97%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%8E%8B%E6%BC%A2%E5%AE%97%E7%89%B9%E9%BB%91%E9%AB%94%E7%B9%81.ttf',
        desc: '「王汉宗自由字型」由研发天蚕字库的台湾中原大学数学系王汉宗教授先分别在2000年和2004年先后捐出十套WCL系列字型和32套新字型，全部以GNU GPL许可分发。'
    },
    WangHanZongTeMingTiFan_Regular: {
        type: '2',
        code: 'wanghanzongtemingtifan',
        name: '王漢宗特明體繁',
        preview: 'images/font/wanghanzongtemingtifan/font.svg',
        posters: ['images/font/wanghanzongtemingtifan/poster.svg'],
        license: 'GPL-2.0',
        auth: false,
        source: 'https://code.google.com/archive/p/wangfonts/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%8E%8B%E6%B1%89%E5%AE%97%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%8E%8B%E6%BC%A2%E5%AE%97%E7%89%B9%E6%98%8E%E9%AB%94%E7%B9%81.ttf',
        desc: '「王汉宗自由字型」由研发天蚕字库的台湾中原大学数学系王汉宗教授先分别在2000年和2004年先后捐出十套WCL系列字型和32套新字型，全部以GNU GPL许可分发。'
    },
    WangHanZongTeYuanTiFan_Regular: {
        type: '4',
        code: 'wanghanzongteyuantifan',
        name: '王漢宗特圓體繁',
        preview: 'images/font/wanghanzongteyuantifan/font.svg',
        posters: ['images/font/wanghanzongteyuantifan/poster.svg'],
        license: 'GPL-2.0',
        auth: false,
        source: 'https://code.google.com/archive/p/wangfonts/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%8E%8B%E6%B1%89%E5%AE%97%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%8E%8B%E6%BC%A2%E5%AE%97%E7%89%B9%E5%9C%93%E9%AB%94%E7%B9%81.ttf',
        desc: '「王汉宗自由字型」由研发天蚕字库的台湾中原大学数学系王汉宗教授先分别在2000年和2004年先后捐出十套WCL系列字型和32套新字型，全部以GNU GPL许可分发。'
    },
    WangHanZongXiHeiTiFan_Regular: {
        type: '1',
        code: 'wanghanzongxiheitifan',
        name: '王漢宗細黑體繁',
        preview: 'images/font/wanghanzongxiheitifan/font.svg',
        posters: ['images/font/wanghanzongxiheitifan/poster.svg'],
        license: 'GPL-2.0',
        auth: false,
        source: 'https://code.google.com/archive/p/wangfonts/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%8E%8B%E6%B1%89%E5%AE%97%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%8E%8B%E6%BC%A2%E5%AE%97%E7%B4%B0%E9%BB%91%E9%AB%94%E7%B9%81.ttf',
        desc: '「王汉宗自由字型」由研发天蚕字库的台湾中原大学数学系王汉宗教授先分别在2000年和2004年先后捐出十套WCL系列字型和32套新字型，全部以GNU GPL许可分发。'
    },
    WangHanZongXiMingTiFan_Regular: {
        type: '2',
        code: 'wanghanzongximingtifan',
        name: '王漢宗細明體繁',
        preview: 'images/font/wanghanzongximingtifan/font.svg',
        posters: ['images/font/wanghanzongximingtifan/poster.svg'],
        license: 'GPL-2.0',
        auth: false,
        source: 'https://code.google.com/archive/p/wangfonts/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%8E%8B%E6%B1%89%E5%AE%97%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%8E%8B%E6%BC%A2%E5%AE%97%E7%B4%B0%E6%98%8E%E9%AB%94%E7%B9%81.ttf',
        desc: '「王汉宗自由字型」由研发天蚕字库的台湾中原大学数学系王汉宗教授先分别在2000年和2004年先后捐出十套WCL系列字型和32套新字型，全部以GNU GPL许可分发。'
    },
    WangHanZongXiXinSongJiAN_Regular: {
        type: '2',
        code: 'wanghanzongxixinsongjian',
        name: '王漢宗細新宋簡',
        preview: 'images/font/wanghanzongxixinsongjian/font.svg',
        posters: ['images/font/wanghanzongxixinsongjian/poster.svg'],
        license: 'GPL-2.0',
        auth: false,
        source: 'https://code.google.com/archive/p/wangfonts/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%8E%8B%E6%B1%89%E5%AE%97%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%8E%8B%E6%BC%A2%E5%AE%97%E7%B4%B0%E6%96%B0%E5%AE%8B%E7%B0%A1.ttf',
        desc: '「王汉宗自由字型」由研发天蚕字库的台湾中原大学数学系王汉宗教授先分别在2000年和2004年先后捐出十套WCL系列字型和32套新字型，全部以GNU GPL许可分发。'
    },
    WangHanZongXiYuanTiFan_Regular: {
        type: '4',
        code: 'wanghanzongxiyuantifan',
        name: '王漢宗細圓體繁',
        preview: 'images/font/wanghanzongxiyuantifan/font.svg',
        posters: ['images/font/wanghanzongxiyuantifan/poster.svg'],
        license: 'GPL-2.0',
        auth: false,
        source: 'https://code.google.com/archive/p/wangfonts/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%8E%8B%E6%B1%89%E5%AE%97%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%8E%8B%E6%BC%A2%E5%AE%97%E7%B4%B0%E5%9C%93%E9%AB%94%E7%B9%81.ttf',
        desc: '「王汉宗自由字型」由研发天蚕字库的台湾中原大学数学系王汉宗教授先分别在2000年和2004年先后捐出十套WCL系列字型和32套新字型，全部以GNU GPL许可分发。'
    },
    WangHanZongYanKaiTiFan_Regular: {
        type: '3',
        code: 'wanghanzongyankaitifan',
        name: '王漢宗顏楷體繁',
        preview: 'images/font/wanghanzongyankaitifan/font.svg',
        posters: ['images/font/wanghanzongyankaitifan/poster.svg'],
        license: 'GPL-2.0',
        auth: false,
        source: 'https://code.google.com/archive/p/wangfonts/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%8E%8B%E6%B1%89%E5%AE%97%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%8E%8B%E6%BC%A2%E5%AE%97%E9%A1%8F%E6%A5%B7%E9%AB%94%E7%B9%81.ttf',
        desc: '「王汉宗自由字型」由研发天蚕字库的台湾中原大学数学系王汉宗教授先分别在2000年和2004年先后捐出十套WCL系列字型和32套新字型，全部以GNU GPL许可分发。'
    },
    WangHanZongZhongFangSongFan_Regular: {
        type: '2',
        code: 'wanghanzongzhongfangsongfan',
        name: '王漢宗中仿宋繁',
        preview: 'images/font/wanghanzongzhongfangsongfan/font.svg',
        posters: ['images/font/wanghanzongzhongfangsongfan/poster.svg'],
        license: 'GPL-2.0',
        auth: false,
        source: 'https://code.google.com/archive/p/wangfonts/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%8E%8B%E6%B1%89%E5%AE%97%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%8E%8B%E6%BC%A2%E5%AE%97%E4%B8%AD%E4%BB%BF%E5%AE%8B%E7%B9%81.ttf',
        desc: '「王汉宗自由字型」由研发天蚕字库的台湾中原大学数学系王汉宗教授先分别在2000年和2004年先后捐出十套WCL系列字型和32套新字型，全部以GNU GPL许可分发。'
    },
    WangHanZongZhongFangSongJian_Regular: {
        type: '2',
        code: 'wanghanzongzhongfangsongjian',
        name: '王漢宗中仿宋簡',
        preview: 'images/font/wanghanzongzhongfangsongjian/font.svg',
        posters: ['images/font/wanghanzongzhongfangsongjian/poster.svg'],
        license: 'GPL-2.0',
        auth: false,
        source: 'https://code.google.com/archive/p/wangfonts/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%8E%8B%E6%B1%89%E5%AE%97%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%8E%8B%E6%BC%A2%E5%AE%97%E4%B8%AD%E4%BB%BF%E5%AE%8B%E7%B0%A1.ttf',
        desc: '「王汉宗自由字型」由研发天蚕字库的台湾中原大学数学系王汉宗教授先分别在2000年和2004年先后捐出十套WCL系列字型和32套新字型，全部以GNU GPL许可分发。'
    },
    WangHanZongZhongKaiTiZhuYin_Regular: {
        type: '3',
        code: 'wanghanzongzhongkaitizhuyin',
        name: '王漢宗中楷體注音',
        preview: 'images/font/wanghanzongzhongkaitizhuyin/font.svg',
        posters: ['images/font/wanghanzongzhongkaitizhuyin/poster.svg'],
        license: 'GPL-2.0',
        auth: false,
        source: 'https://code.google.com/archive/p/wangfonts/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%8E%8B%E6%B1%89%E5%AE%97%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%8E%8B%E6%BC%A2%E5%AE%97%E4%B8%AD%E6%A5%B7%E9%AB%94%E6%B3%A8%E9%9F%B3.ttf',
        desc: '「王汉宗自由字型」由研发天蚕字库的台湾中原大学数学系王汉宗教授先分别在2000年和2004年先后捐出十套WCL系列字型和32套新字型，全部以GNU GPL许可分发。'
    },
    WangHanZongZhongMingTiZhuYin_Regular: {
        type: '2',
        code: 'wanghanzongzhongmingtizhuyin',
        name: '王漢宗中明體注音',
        preview: 'images/font/wanghanzongzhongmingtizhuyin/font.svg',
        posters: ['images/font/wanghanzongzhongmingtizhuyin/poster.svg'],
        license: 'GPL-2.0',
        auth: false,
        source: 'https://code.google.com/archive/p/wangfonts/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%8E%8B%E6%B1%89%E5%AE%97%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%8E%8B%E6%BC%A2%E5%AE%97%E4%B8%AD%E6%98%8E%E9%AB%94%E6%B3%A8%E9%9F%B3.ttf',
        desc: '「王汉宗自由字型」由研发天蚕字库的台湾中原大学数学系王汉宗教授先分别在2000年和2004年先后捐出十套WCL系列字型和32套新字型，全部以GNU GPL许可分发。'
    },
    WangHanZongZhongLiShuFan_Regular: {
        type: '4',
        code: 'wanghanzongzhonglishufan',
        name: '王漢宗中隸書繁',
        preview: 'images/font/wanghanzongzhonglishufan/font.svg',
        posters: ['images/font/wanghanzongzhonglishufan/poster.svg'],
        license: 'GPL-2.0',
        auth: false,
        source: 'https://code.google.com/archive/p/wangfonts/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%8E%8B%E6%B1%89%E5%AE%97%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%8E%8B%E6%BC%A2%E5%AE%97%E4%B8%AD%E9%9A%B8%E6%9B%B8%E7%B9%81.ttf',
        desc: '「王汉宗自由字型」由研发天蚕字库的台湾中原大学数学系王汉宗教授先分别在2000年和2004年先后捐出十套WCL系列字型和32套新字型，全部以GNU GPL许可分发。'
    },
    WangHanZongZhongMingTiFan_Regular: {
        type: '2',
        code: 'wanghanzongzhongmingtifan',
        name: '王漢宗中明體繁',
        preview: 'images/font/wanghanzongzhongmingtifan/font.svg',
        posters: ['images/font/wanghanzongzhongmingtifan/poster.svg'],
        license: 'GPL-2.0',
        auth: false,
        source: 'https://code.google.com/archive/p/wangfonts/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%8E%8B%E6%B1%89%E5%AE%97%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%8E%8B%E6%BC%A2%E5%AE%97%E4%B8%AD%E6%98%8E%E9%AB%94%E7%B9%81.ttf',
        desc: '「王汉宗自由字型」由研发天蚕字库的台湾中原大学数学系王汉宗教授先分别在2000年和2004年先后捐出十套WCL系列字型和32套新字型，全部以GNU GPL许可分发。'
    },
    WangHanZongZhongWeiBeiJian_Regular: {
        type: '4',
        code: 'wanghanzongzhongweibeijian',
        name: '王漢宗中魏碑簡',
        preview: 'images/font/wanghanzongzhongweibeijian/font.svg',
        posters: ['images/font/wanghanzongzhongweibeijian/poster.svg'],
        license: 'GPL-2.0',
        auth: false,
        source: 'https://code.google.com/archive/p/wangfonts/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%8E%8B%E6%B1%89%E5%AE%97%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%8E%8B%E6%BC%A2%E5%AE%97%E4%B8%AD%E9%AD%8F%E7%A2%91%E7%B0%A1.ttf',
        desc: '「王汉宗自由字型」由研发天蚕字库的台湾中原大学数学系王汉宗教授先分别在2000年和2004年先后捐出十套WCL系列字型和32套新字型，全部以GNU GPL许可分发。'
    },
    WangHanZongZhongXingShuFan_Regular: {
        type: '4',
        code: 'wanghanzongzhongxingshufan',
        name: '王漢宗中行書繁',
        preview: 'images/font/wanghanzongzhongxingshufan/font.svg',
        posters: ['images/font/wanghanzongzhongxingshufan/poster.svg'],
        license: 'GPL-2.0',
        auth: false,
        source: 'https://code.google.com/archive/p/wangfonts/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%8E%8B%E6%B1%89%E5%AE%97%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%8E%8B%E6%BC%A2%E5%AE%97%E4%B8%AD%E8%A1%8C%E6%9B%B8%E7%B9%81.ttf',
        desc: '「王汉宗自由字型」由研发天蚕字库的台湾中原大学数学系王汉宗教授先分别在2000年和2004年先后捐出十套WCL系列字型和32套新字型，全部以GNU GPL许可分发。'
    },
    WangHanZongZongYiTiFan_Regular: {
        type: '4',
        code: 'wanghanzongzongyitifan',
        name: '王漢宗綜藝體繁',
        preview: 'images/font/wanghanzongzongyitifan/font.svg',
        posters: ['images/font/wanghanzongzongyitifan/poster.svg'],
        license: 'GPL-2.0',
        auth: false,
        source: 'https://code.google.com/archive/p/wangfonts/',
        download: 'https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E7%8E%8B%E6%B1%89%E5%AE%97%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E7%8E%8B%E6%BC%A2%E5%AE%97%E7%B6%9C%E8%97%9D%E9%AB%94%E7%B9%81.ttf',
        desc: '「王汉宗自由字型」由研发天蚕字库的台湾中原大学数学系王汉宗教授先分别在2000年和2004年先后捐出十套WCL系列字型和32套新字型，全部以GNU GPL许可分发。'
    },
    QuanZiKuZhengKaiTi_Regular: {
        type: '3',
        code: 'quanzikuzhengkaiti',
        name: '全字庫正楷體',
        preview: 'images/font/quanzikuzhengkaiti/font.svg',
        posters: ['images/font/quanzikuzhengkaiti/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://www.cns11643.gov.tw/pageView.jsp?ID=59',
        download: '',
        desc: '「全字库字体」是台湾地区为了解决电脑中文字数不足而做的一款开源字体，供全社会免费商用。'
    },
    QuanZiKuZhengSongTi_Regular: {
        type: '2',
        code: 'quanzikuzhengsongti',
        name: '全字庫正宋體',
        preview: 'images/font/quanzikuzhengsongti/font.svg',
        posters: ['images/font/quanzikuzhengsongti/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://www.cns11643.gov.tw/pageView.jsp?ID=59',
        download: '',
        desc: '「全字库字体」是台湾地区为了解决电脑中文字数不足而做的一款开源字体，供全社会免费商用。'
    },
    QuanZiKuShuoWenJieZi_Regular: {
        type: '4',
        code: 'quanzikushuowenjiezi',
        name: '全字庫說文解字',
        preview: 'images/font/quanzikushuowenjiezi/font.svg',
        posters: ['images/font/quanzikushuowenjiezi/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://www.cns11643.gov.tw/pageView.jsp?ID=59',
        download: '',
        desc: '「全字库字体」是台湾地区为了解决电脑中文字数不足而做的一款开源字体，供全社会免费商用。'
    },
    ChogokubosoGothic_Regular: {
        type: '4',
        code: 'chogokubosogothic',
        name: '超极细',
        preview: 'images/font/chogokubosogothic/font.svg',
        posters: ['images/font/chogokubosogothic/poster.svg'],
        license: '商免',
        auth: false,
        source: 'http://font.websozai.jp/line-font-mihon.html',
        download: '',
        desc: '「超极细」日文称为【超極細ゴシック体】，据说是目前字体线条最细的一款字体。超极细本身是日文字体，但同时支持繁体，所以也可作繁体字体使用。'
    },
    AlibabaPuHuiTi_Regular: {
        type: '4',
        code: 'alibabapuhuiti',
        name: '阿里巴巴普惠体',
        preview: 'images/font/alibabapuhuiti/font.svg',
        posters: ['images/font/alibabapuhuiti/poster.svg'],
        license: '商免',
        auth: false,
        source: 'https://ics.alibaba.com/space/H7rlDe?spm=ics.preview.0.0.242063a8wIReE8',
        download: 'https://ics.alibaba.com/asset/download?spm=ics.preview.0.0.572863a8Ukyybl&id=28c06e8d05462a16',
        desc: '「阿里巴巴普惠体」由阿里巴巴在举办的 「2019 阿里巴巴UCAN 设计大会」发布了，该字体是永久免费商用。'
    }



};