document.writeln("<div class=\"row\">");
document.writeln("	<div class=\"col-sm-3 col-md-3\">");
document.writeln("		<a class=\"footer-logo\" href=\"index.html\">&nbsp;<\/a>");
document.writeln("	<\/div>");
document.writeln("	<div class=\"col-sm-3 col-md-3 col-xs-4\">");
document.writeln("		<a class=\"bold padding\" href=\"index.html\">字体产品<\/a>");
document.writeln("		<a class=\"bold-link\" href=\"index.html?hei\">黑体系列<\/a>");
document.writeln("		<a class=\"bold-link\" href=\"index.html?song\">宋体系列<\/a>");
document.writeln("		<a class=\"bold-link\" href=\"index.html?kai\">楷体系列<\/a>");
document.writeln("		<a class=\"bold-link\" href=\"index.html?yishu\">艺术字体<\/a>");
document.writeln("		<a class=\"bold-link\" href=\"index.html?shouhui\">手绘字体<\/a>");
document.writeln("	<\/div>");
document.writeln("	<div class=\"col-sm-3 col-md-3 col-xs-4\">");
document.writeln("		<a class=\"bold padding\" href=\"about.html\">关于我们<\/a>");
document.writeln("	<\/div>");
document.writeln("	<div class=\"col-sm-3 col-md-3 col-xs-4\">");
document.writeln("		<a class=\"bold padding\" href=\"authorization.html\">关于授权<\/a>");
document.writeln("	<\/div>");
document.writeln("");
document.writeln("<\/div>");
document.writeln("<div class=\"ie-bottom-line-hacker\"><\/div>");
